# Generated by Django 4.1.3 on 2022-12-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
