# Generated by Django 4.1.3 on 2022-12-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
