# Generated by Django 4.1.3 on 2022-12-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_measure_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='title',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
